CREATE PARTITION FUNCTION [pfPartitionKeyYearMonth]
	(
		INT
	)
	AS RANGE RIGHT   
	FOR VALUES 
	(
		YEAR(DATEADD(MONTH, 6, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,6, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, 5, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,5, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, 4, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,4, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, 3, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,3, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, 2, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,2, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, 1, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,1, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, 0, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,0, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -1, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-1, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -2, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-2, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -3, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-3, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -4, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-4, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -5, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-5, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -6, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-6, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -7, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-7, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -8, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-8, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -9, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-9, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -10, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-10, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -11, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-11, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -12, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-12, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -13, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-13, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -14, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-14, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -15, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-15, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -16, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-16, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -17, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-17, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -18, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-18, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -19, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-19, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -20, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-20, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -21, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-21, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -22, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-22, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -23, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-23, SYSUTCDATETIME())), 
		YEAR(DATEADD(MONTH, -24, SYSUTCDATETIME())) *100 + MONTH(DATEADD(MONTH,-24, SYSUTCDATETIME()))
	)
